### ISSUE TITLE
b4msa with default parameters on a particular data set

### ISSUE THREAD

**Issue by mgraffg** [INGEOTEC/b4msa#3]
Let us try b4msa on tass2015 dataset.
* install b4msa
* get tass2015 dataset
* use b4msa command line

**Comment by oskrsasi** [comment]
Now b4amsa can read XML (TASS 2015 format) files. A test file has been included in the test folder:

b4msa b4msa/tests/text.xml -k 2

Some more tests to do for this issue.

**Comment by oskrsasi** [comment]
Closed as @sadit tested on tass2015 dataset
