### ISSUE TITLE
Global / Local installation...

### ISSUE THREAD

**Issue by oskrsasi** [INGEOTEC/b4msa#6]
As the script "_miniconda.sh_" will install minianaconda3 at "_/home/$USER/miniconda3/bin_", both installation commands: 

`python setup.py install`

and

`python setup.py install --user`

will install **_b4msa_** only for the user.

The first one will install packages at "_/home/$USER/miniconda3/bin_" and the second one at "_/home/$USER/.local/bin_".

Tested on Ubuntu 14.04.1 / Gnome / 3.19.0-25-generic

**Comment by mgraffg** [comment]
This simplifies the process, I will change the readme.

**Comment by mgraffg** [comment]
done.
